---
title: "delta8tweets"
author: "Drew Walker"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
bibliography: references.bib
---

# Tidy Adaptation

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#remotes::install_github("slu-openGIS/postmastr")
library(table1)
library(operators)
library(magrittr)
library(stm)
library(here)
library(postmastr)
library(textmineR)
library(tidyverse)
library(tidytext)
library(knitr) #Create nicely formatted output tables
library(kableExtra) #Create nicely formatted output tables
library(formattable) #For the color_tile function
library(lubridate)
library(academictwitteR)
library(tm)
library(tidygeocoder)
library(ggpubr)
library(topicmodels)
library(scales)
library(gt)
library(webshot)
library(sentimentr)
library(syuzhet)
library(gitcreds)
library(credentials)


APIToken <- read_csv("apikeys.csv")
api_key <- as.character(APIToken[1,1])
api_secret_key <- as.character(APIToken[1,2])
bearer_token <- as.character(APIToken[1,3])
```


# Pull tweet full archive tweet data

-   Add search by hashtag

```{r get-hashtag-delta8-tweets}
#
##Get tweets with Delta 8 thc or delta 8 hashtag

today <- as.POSIXct(Sys.Date())
hashtag_delta8_tweets_jan_2020 <-  get_all_tweets(
  query = "#delta8",
  start_tweets = "2020-01-01T00:00:00Z",
  end_tweets = "2021-09-24T00:00:00Z",
  bearer_token,data_path = "data/",
  n = 100000)

users_hashtag_d8_tweets_jan_2020 <-
get_user_profile(unique(hashtag_delta8_tweets_jan_2020$author_id), bearer_token)
#
users_hashtag_d8_tweets_jan_2020 <- users_hashtag_d8_tweets_jan_2020 %>% 
  rename(author_id = id)
#
#
hashtag_delta8_tweets_and_user_info_jan_2020 <- left_join(hashtag_delta8_tweets_jan_2020, users_hashtag_d8_tweets_jan_2020, by = "author_id")

write_rds(hashtag_delta8_tweets_and_user_info_jan_2020, "hashtag_delta8_tweets_and_user_info_jan_2020.rds")
```
# Sensitivity analysis for initial corpus collection
Tweets also pulled for those containing:
* #delta-8 #delta 8
* co-use of hashtags 
```{r}
#dash_delta8_tweets_jan_2020 <-  get_all_tweets(
 # query = "#delta-8",
 #start_tweets = "2020-01-01T00:00:00Z",
 # end_tweets = "2021-09-24T00:00:00Z",
 #bearer_token,data_path = "data/",
 #  n = 100000)

#space_delta8_tweets_jan_2020 <-  get_all_tweets(
 #  query = "delta 8",
 #  start_tweets = "2020-01-01T00:00:00Z",
 #  end_tweets = "2021-09-24T00:00:00Z",
 #  bearer_token,data_path = "data/",
 #  n = 100000)
```

