---
title: "delta8tweets"
author: "Drew Walker"
date: "6/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(academictwitteR)
APIToken <- read_csv("apikeys.csv")
api_key <- as.character(APIToken[1,1])
api_secret_key <- as.character(APIToken[1,2])
bearer_token <- as.character(APIToken[1,3])
```

# Pull tweet full archive tweet data 
```{r apitokens}



# d8_tweets_jan_2021 <-
#   get_all_tweets("delta 8 thc",
#                  "2021-01-01T00:00:00Z",
#                  "2021-06-09T00:00:00Z",
#                  bearer_token)
# 
# write_rds(d8_tweets_jan_2021, "d8_tweets_since_jan_2021.rds")


d8_tweets_jan_2020 <-  get_all_tweets("delta 8 thc",
                 "2020-01-01T00:00:00Z",
                 "2021-06-10T00:00:00Z",
                 bearer_token)

write_rds(d8_tweets_jan_2020, "d8_tweets_since_jan_2020.rds")


users_d8_tweets_jan_2020 <-
  get_user_profile(unique(d8_tweets_jan_2020$author_id), bearer_token)

users_d8_tweets_jan_2020 <- users_d8_tweets_jan_2020 %>% 
  rename(author_id = id)


d8_tweets_and_user_info_jan_2020 <- left_join(d8_tweets_jan_2020, users_d8_tweets_jan_2020, by = "author_id")

```
# Tweet data analysis 

```{r delta8tweets}


```




